# These are supported funding model platforms

[shubhanshu24510]: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
[shubhanshu24510]: # Replace with a single Patreon username
[shubhanshu24510]: # Replace with a single Open Collective username
[shubhanshu24510]: # Replace with a single Ko-fi username
[shubhanshu24510]: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
[shubhanshu24510]: # Replace with a single Community Bridge project-name e.g., cloud-foundry
[shubhanshu24510]: # Replace with a single Liberapay username
[shubhanshu24510]: # Replace with a single IssueHunt username
[shubhanshu24510]: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
[shubhanshu24510]: # Replace with a single Polar username
[shubhanshu24510]: # Replace with a single Buy Me a Coffee username
[shubhanshu24510]: # Replace with a single thanks.dev username
[shubhanshu24510]: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
